version: '3.1'
services:
  jenkins:
    restart: always
    image: jenkins/jenkins
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      TZ: Asia/Shanghaid
    volumes:
      - ./data:/var/jenkins_home
  nginx:
    image: nginx
    restart: always
    hostname: nginx
    container_name: nginx
    privileged: true
    ports:
      - 80:80
    volumes:
      - ./nginx/conf/nginx/:/etc/nginx/
      - ./data/workspace/cxf/dist/:/usr/share/nginx/html/
    build: ./python
    ports:
     - "8090:5000"
  redis:
    image: "redis:alpine"
          